name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  docker-build-push:
    name: Build & Push Docker Image
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t myapp:${{ github.sha }} .

      - name: Tag and Push Image
        run: |
          docker tag myapp:${{ github.sha }} mydockerhubusername/myapp:${{ github.sha }}
          docker push mydockerhubusername/myapp:${{ github.sha }}

  deploy:
    name: Deploy to GKE
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up kubectl
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials my-cluster --region us-central1 --project my-gcp-project
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl set image deployment/my-app my-app=mydockerhubusername/myapp:${{ github.sha }}
